version: "3.9"
services: 
    app:
        build: 
            context: .
            target: frontend
        depends_on: 
            - api
        networks:
            - my_network
    api:
        build: 
            context: .
            target: backend
        ports: 
            - 3000:3000
        depends_on: 
            - db
        environment:
            DATABASE_NAME: docker
            DATABASE_USERNAME: docker
            DATABASE_PASSWORD: ${DB_PASSWORD}
            DATABASE_URL: db
        networks:
            - my_network

    db:
        build: ./server/util/db
        ports: 
            - 5432:5432
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_db: docker
        volumes: 
            - db:/var/lib/postgresql/data
        networks:
            - my_network                                                                                 
volumes:
  db:
    driver: local
                                                                                       
networks:                                                                              
  my_network:     