version: "3.9"
services:
  app:
    image: ghcr.io/ido123ziv/openu-web-develop-20995/app:latest
    build:
      context: client
      target: development
    ports:
      - 5173:5173
    depends_on:
      - api
    volumes:
      - ./client:/app/
      - /app/node_modules
    networks:
      - my_network
  api:
    image: ghcr.io/ido123ziv/openu-web-develop-20995/api:latest
    restart: always
    build:
      context: server
      target: development
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_NAME: ${DB_NAME:-docker}
      DATABASE_USERNAME: ${DB_USERNAME:-docker}
      DATABASE_PASSWORD: ${DB_PASSWORD:-1234}
      DATABASE_URL: db
      DATABASE_PORT: ${DB_PORT:-5432}
    volumes:
      - ./server:/app/
      - /app/node_modules
    networks:
      - my_network

  db:
    image: ghcr.io/ido123ziv/openu-web-develop-20995/db:latest
    build: ./db
    ports:
      - target: 5432
        published: ${DB_PORT:-5432}
        protocol: tcp
    environment:
      POSTGRES_USER: ${DB_USERNAME:-docker}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_db: ${DB_NAME:-docker}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my_network
volumes:
  db:
    driver: local

networks:
  my_network:
