name: Create and publish a Docker image
run-name: "Build Images for ${{ github.ref_name }}"
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:
  push:
    branches: ['main', 'feat/docker-seperation']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: 
        images: ["app", "api", "db"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: get context from name
        id: context
        run: |
            if [[ "${{ matrix.images }}" =~ "app" ]]; then
                echo "context=./client" >> $GITHUB_OUTPUT
            elif [[ "${{matrix.images}}" =~ "api" ]]; then
                echo "context=./server" >> $GITHUB_OUTPUT
            else
                echo "context=./server/utils/db" >> $GITHUB_OUTPUT
            fi
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavors: |
            latest=auto
            prefix=${{matrix.images}}
          tags: |
            type=ref,event=branch
      - name: Build and push ${{ matrix.images }}
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ steps.context.outputs.context }}
          push: true
          target: development
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
